### ISSUE TITLE
links to previous weeks broken?

### ISSUE THREAD

**Issue by dflatow** [compjour/compjour-class-site#1]
On the homepage the links to previous weeks are broken (they just link to http://www.compjour.org/#)

![screenshot 2015-04-15 14 59 52](https://cloud.githubusercontent.com/assets/5514147/7170118/2d260602-e380-11e4-8980-8d5008e8b265.png)

Maybe an issue in: content_partials/weeks/_past_weeks.slim?

**Comment by dflatow** [comment]
@dannguyen hey

**Comment by dannguyen** [comment]
Whoops, thanks!
